---
# tasks file for first-run
- name: First-Run | Main | Run raw command to install python for rest of plays
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)


